import type { Wine } from '../types/wine';

export const wines: Wine[] = [
  {
    id: 1,
    title: 'Chateau Ste. Michelle Cabernet Sauvignon',
    country: 'France',
    type: 'Red',
    region: 'Bordeaux',
    volume: 750,
    price: 20,
  },
  {
    id: 2,
    title: 'Wine 2',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 3,
    title: 'Wine 3',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 4,
    title: 'Wine 4',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 5,
    title: 'Wine 5',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 6,
    title: 'Wine 6',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 7,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 8,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 9,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 10,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
  {
    id: 11,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    region: 'Tuscany',
    volume: 750,
    price: 25,
  },
];
