import type { Wine } from '../types/wine';

export const wines: Wine[] = [
  {
    id: 1,
    title: 'Chateau Ste. Michelle Cabernet Sauvignon',
    country: 'France',
    type: 'Red',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Bordeaux',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 20,
  },
  {
    id: 2,
    title: 'Wine 2',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 3,
    title: 'Wine 3',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 4,
    title: 'Wine 4',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 5,
    title: 'Wine 5',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 6,
    title: 'Wine 6',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 7,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 8,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 9,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 10,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
  {
    id: 11,
    title: 'Wine 7',
    country: 'Italy',
    type: 'White',
    aroma: ['black cheries', 'mocha', 'spices'],
    aging: 2020,
    region: 'Tuscany',
    volume: 750,
    perfectFit: 'Grilled ribeye steak with a rosemary garlic butter sauce',
    description:
      'Known for its consistency and quality, this wine offers great value as an accessible yet sophisticated Cabernet Sauvignon. It can be enjoyed now or aged for added complexity.',
    price: 25,
  },
];
